// web/src/lib/views/ArchivedView.tsx
// Экран архива (URL /archive): заметки из всех топиков.
// Открытие заметки — полноэкранная «страница» (NotePage): вернуть из архива /
// удалить. Возврат на главный экран — стрелка в шапке.
import { useEffect, useMemo, useState } from 'react';

import { EmptyState } from '../components/EmptyState';
import { Loader } from '../components/Loader';
import { NoteCard } from '../components/NoteCard';
import { NoteMenu } from '../components/NoteMenu';
import { NotePage } from '../components/NotePage';
import { loadArchived, useNotesStore } from '../stores/notes';
import { logout } from '../stores/session';
import type { Note } from '../types/api';
import { navigate } from '../router';

export function ArchivedView() {
  const archivedNotes = useNotesStore((s) => s.archivedNotes);
  const archivedLoading = useNotesStore((s) => s.archivedLoading);
  const archivedError = useNotesStore((s) => s.archivedError);

  // Открытая заметка: кэш объекта — заметка может исчезнуть из списка
  // (вернуть из архива/удалить) раньше, чем доиграет закрытие страницы.
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [selectedCache, setSelectedCache] = useState<Note | null>(null);
  useEffect(() => {
    if (selectedId === null) {
      setSelectedCache(null);
      return;
    }
    const found = archivedNotes.find((n) => n.id === selectedId);
    if (found) setSelectedCache(found);
  }, [selectedId, archivedNotes]);

  // Дропдаун-меню (долгий тач по карточке): заметка + позиция карточки в момент открытия.
  const [menuNoteId, setMenuNoteId] = useState<number | null>(null);
  const [menuRect, setMenuRect] = useState<DOMRect | null>(null);
  const menuNote = useMemo(
    () => menuNoteId === null ? null : archivedNotes.find((n) => n.id === menuNoteId) ?? null,
    [menuNoteId, archivedNotes],
  );

  function openMenu(note: Note, rect: DOMRect): void {
    setMenuNoteId(note.id);
    setMenuRect(rect);
  }

  function closeMenu(): void {
    setMenuNoteId(null);
    setMenuRect(null);
  }

  function closePage(): void {
    setSelectedId(null);
  }

  useEffect(() => {
    void loadArchived();
  }, []);

  async function doLogout(): Promise<void> {
    await logout();
    navigate('/login');
  }

  return (
    <>
      <div className="flex h-full flex-col">
        <header className="flex shrink-0 items-center justify-between border-b border-border bg-background px-3 pt-[env(safe-area-inset-top)]">
          <button
            type="button"
            aria-label="Назад"
            className="flex h-10 w-10 items-center justify-center rounded-full text-lg active:bg-border/50"
            onClick={() => navigate('/')}
          >
            ←
          </button>
          <span className="text-xl">🗄</span>
          <button
            type="button"
            aria-label="Выйти"
            className="flex h-10 w-10 items-center justify-center rounded-full text-lg active:bg-border/50"
            onClick={() => void doLogout()}
          >
            🚪
          </button>
        </header>

        <main className="scroll-area flex-1 overflow-y-auto">
          {archivedLoading ? (
            <Loader />
          ) : archivedError ? (
            <div className="flex flex-col items-center gap-4 px-6 py-16">
              <EmptyState emoji="⚠️" text={archivedError} />
              <button
                type="button"
                className="h-11 rounded-xl border border-border px-6 text-sm"
                onClick={() => void loadArchived()}
              >
                Повторить
              </button>
            </div>
          ) : archivedNotes.length === 0 ? (
            <EmptyState emoji="🗄" text="Архив пуст" />
          ) : (
            <div className="flex flex-col gap-2 px-3 py-3">
              {archivedNotes.map((note) => (
                <NoteCard key={note.id} note={note} onOpen={(n) => setSelectedId(n.id)} onMenu={openMenu} />
              ))}
            </div>
          )}
        </main>
      </div>

      {selectedCache !== null && <NotePage note={selectedCache} onClose={closePage} />}

      {menuNote !== null && menuRect !== null && (
        <NoteMenu note={menuNote} rect={menuRect} archived onClose={closeMenu} />
      )}
    </>
  );
}

// web/src/views/ArchivedView.svelte
<script lang="ts">
  // Экран архива: заметки из всех топиков. Действия — вернуть / удалить.
  import { onMount } from 'svelte';
  import EmptyState from '../lib/components/EmptyState.svelte';
  import Modal from '../lib/components/Modal.svelte';
  import NoteCard from '../lib/components/NoteCard.svelte';
  import { showChat } from '../lib/stores/navigation.svelte';
  import {
    archivedStore,
    loadArchived,
    removeArchivedNote,
    unarchiveNote,
  } from '../lib/stores/notes.svelte';
  import type { Note } from '../lib/types/api';

  let selectedId: number | null = $state(null);
  const selectedNote = $derived(
    selectedId === null
      ? null
      : archivedStore.notes.find((n) => n.id === selectedId) ?? null,
  );

  let busy = $state(false);
  let error = $state('');
  let confirmDelete = $state(false);

  onMount(() => {
    void loadArchived();
  });

  async function doUnarchive(note: Note): Promise<void> {
    busy = true;
    error = '';
    try {
      await unarchiveNote(note);
      selectedId = null;
    } catch (e) {
      error = e instanceof Error ? e.message : 'ошибка';
    } finally {
      busy = false;
    }
  }

  async function doDelete(note: Note): Promise<void> {
    busy = true;
    error = '';
    try {
      await removeArchivedNote(note);
      selectedId = null;
    } catch (e) {
      error = e instanceof Error ? e.message : 'ошибка';
    } finally {
      busy = false;
    }
  }
</script>

<div class="flex h-full flex-col">
  <header
    class="flex shrink-0 items-center justify-between border-b border-border bg-surface px-3 pt-[env(safe-area-inset-top)]"
  >
    <button
      type="button"
      aria-label="Назад"
      class="flex h-10 w-10 items-center justify-center rounded-full text-lg active:bg-border/50"
      onclick={showChat}
    >
      ←
    </button>
    <span class="text-xl">🗄</span>
    <span class="w-10"></span>
  </header>

  <main class="flex-1 overflow-y-auto">
    {#if archivedStore.loading}
      <EmptyState emoji="⏳" />
    {:else if archivedStore.error}
      <div class="flex flex-col items-center gap-4 px-6 py-16">
        <EmptyState emoji="⚠️" text={archivedStore.error} />
        <button
          type="button"
          class="h-11 rounded-xl border border-border px-6 text-sm"
          onclick={() => void loadArchived()}
        >
          Повторить
        </button>
      </div>
    {:else if archivedStore.notes.length === 0}
      <EmptyState emoji="🗄" text="Архив пуст" />
    {:else}
      <div class="flex flex-col gap-2 px-3 py-3">
        {#each archivedStore.notes as note (note.id)}
          <NoteCard {note} onOpen={(n) => (selectedId = n.id)} />
        {/each}
      </div>
    {/if}
  </main>
</div>

{#if selectedNote !== null}
  <Modal open onClose={() => (selectedId = null)}>
    {#if confirmDelete}
      <div class="flex flex-col gap-4 px-1 py-2">
        <h2 class="text-lg font-semibold">Удалить заметку?</h2>
        {#if error}
          <p class="text-sm text-danger">{error}</p>
        {/if}
        <div class="flex gap-2">
          <button
            type="button"
            class="h-11 flex-1 rounded-xl border border-border text-sm"
            onclick={() => {
              confirmDelete = false;
              error = '';
            }}
          >
            Отмена
          </button>
          <button
            type="button"
            class="h-11 flex-1 rounded-xl bg-danger text-sm font-medium text-white disabled:opacity-50"
            disabled={busy}
            onclick={() => doDelete(selectedNote)}
          >
            Удалить
          </button>
        </div>
      </div>
    {:else}
      <div class="flex flex-col gap-4 px-1 py-2">
        <p
          class="max-h-64 overflow-y-auto whitespace-pre-wrap break-words text-[15px] leading-6 {selectedNote
            .done
            ? 'text-muted line-through'
            : 'text-content'}"
        >
          {selectedNote.text}
        </p>
        {#if error}
          <p class="text-sm text-danger">{error}</p>
        {/if}
        <div class="flex items-center justify-between gap-1">
          <button
            type="button"
            aria-label="Вернуть из архива"
            class="flex h-11 w-11 items-center justify-center rounded-full bg-background text-lg"
            disabled={busy}
            onclick={() => doUnarchive(selectedNote)}
          >
            ↩️
          </button>
          <button
            type="button"
            aria-label="Удалить"
            class="flex h-11 w-11 items-center justify-center rounded-full bg-background text-lg"
            disabled={busy}
            onclick={() => {
              confirmDelete = true;
              error = '';
            }}
          >
            🗑
          </button>
        </div>
      </div>
    {/if}
  </Modal>
{/if}
