// web/src/lib/views/TimersView.svelte
<script lang="ts">
  // Экран «⏰ Таймеры» (URL /timers): все заметки с установленным напоминанием,
  // из любых топиков — как /timers в боте. Каждая строка: ✅ выполненной +
  // превью + время напоминания и режим (🔂 разовый / 🔁 ежедневный).
  // Приоритет — цветная обводка строки (note-priority-*), как в списке заметок.
  // Тап по строке — полноэкранная «страница» заметки (NotePage).
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import Loader from '$lib/components/Loader.svelte';
  import NotePage from '$lib/components/NotePage.svelte';
  import { loadTimers, timersStore } from '$lib/stores/notes.svelte';
  import { logout } from '$lib/stores/session.svelte';
  import type { Note } from '$lib/types/api';
  import { firstLineHtml, formatReminderAt } from '$lib/utils/format';

  // Открытая заметка: кэш объекта — заметка может исчезнуть из списка
  // (таймер снят/выполнена/удалена) раньше, чем доиграет закрытие страницы.
  let selectedId: number | null = $state(null);
  let selectedCache: Note | null = $state(null);
  $effect(() => {
    if (selectedId === null) {
      selectedCache = null;
      return;
    }
    const found = timersStore.notes.find((n) => n.id === selectedId);
    if (found) selectedCache = found;
  });

  function closePage(): void {
    selectedId = null;
  }

  onMount(() => {
    void loadTimers();
  });

  async function doLogout(): Promise<void> {
    await logout();
    await goto('/login');
  }
</script>

<div class="flex h-full flex-col">
  <header
    class="flex shrink-0 items-center justify-between border-b border-border bg-surface px-3 pt-[env(safe-area-inset-top)]"
  >
    <button
      type="button"
      aria-label="Назад"
      class="flex h-10 w-10 items-center justify-center rounded-full text-lg active:bg-border/50"
      onclick={() => void goto('/')}
    >
      ←
    </button>
    <span class="text-xl">⏰</span>
    <button
      type="button"
      aria-label="Выйти"
      class="flex h-10 w-10 items-center justify-center rounded-full text-lg active:bg-border/50"
      onclick={() => void doLogout()}
    >
      🚪
    </button>
  </header>

  <main class="scroll-area flex-1 overflow-y-auto">
    {#if timersStore.loading}
      <Loader />
    {:else if timersStore.error}
      <div class="flex flex-col items-center gap-4 px-6 py-16">
        <EmptyState emoji="⚠️" text={timersStore.error} />
        <button
          type="button"
          class="h-11 rounded-xl border border-border px-6 text-sm"
          onclick={() => void loadTimers()}
        >
          Повторить
        </button>
      </div>
    {:else if timersStore.notes.length === 0}
      <EmptyState emoji="⏰" text="Таймеров нет" />
    {:else}
      <div class="flex flex-col gap-2 px-3 py-3">
        {#each timersStore.notes as note (note.id)}
          <!-- Тап по строке — страница заметки (там снимают/переносят таймер) -->
          <button
            type="button"
            class="glass-card flex w-full touch-manipulation select-none flex-col gap-1 rounded-2xl px-4 py-3 text-left shadow-sm transition-[background-color,transform] active:scale-[0.98] [-webkit-touch-callout:none] {note.priority ===
            'high'
              ? 'note-priority-high'
              : note.priority === 'medium'
                ? 'note-priority-medium'
                : note.priority === 'low'
                  ? 'note-priority-low'
                  : ''}"
            onclick={() => (selectedId = note.id)}
          >
            <span class="flex min-w-0 items-start gap-2.5">
              {#if note.done}
                <span class="w-5 shrink-0 text-center text-sm leading-6">✅</span>
              {/if}
              <span
                class="line-clamp-2 min-w-0 flex-1 break-words text-[15px] leading-6 {note.done
                  ? 'text-muted line-through'
                  : 'text-content'}"
              >
                {@html firstLineHtml(note.text, note.entities)}
              </span>
            </span>
            <span class="pl-7 text-xs text-muted">
              ⏰ {formatReminderAt(note.reminder_at!, note.reminder_repeat)}
              {note.reminder_repeat === 'daily' ? '· 🔁 ежедневно' : '· 🔂 один раз'}
            </span>
          </button>
        {/each}
      </div>
    {/if}
  </main>
</div>

{#if selectedCache !== null}
  <NotePage note={selectedCache} onClose={closePage} />
{/if}

// web/src/lib/views/TimersView.tsx
// Экран «⏰ Таймеры» (URL /timers): все заметки с установленным напоминанием,
// из любых топиков — как /timers в боте. Каждая строка: ✅ выполненной +
// превью + время напоминания и режим (🔂 разовый / 🔁 ежедневный).
// Приоритет — цветная обводка строки (note-priority-*), как в списке заметок.
// Тап по строке — полноэкранная «страница» заметки (NotePage).
import { useEffect, useState } from 'react';

import { EmptyState } from '../components/EmptyState';
import { Loader } from '../components/Loader';
import { NotePage } from '../components/NotePage';
import { loadTimers, useNotesStore } from '../stores/notes';
import { logout } from '../stores/session';
import type { Note } from '../types/api';
import { firstLineHtml, formatReminderAt } from '../utils/format';
import { navigate } from '../router';

export function TimersView() {
  const timersNotes = useNotesStore((s) => s.timersNotes);
  const timersLoading = useNotesStore((s) => s.timersLoading);
  const timersError = useNotesStore((s) => s.timersError);

  // Открытая заметка: кэш объекта — заметка может исчезнуть из списка
  // (таймер снят/выполнена/удалена) раньше, чем доиграет закрытие страницы.
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [selectedCache, setSelectedCache] = useState<Note | null>(null);
  useEffect(() => {
    if (selectedId === null) {
      setSelectedCache(null);
      return;
    }
    const found = timersNotes.find((n) => n.id === selectedId);
    if (found) setSelectedCache(found);
  }, [selectedId, timersNotes]);

  function closePage(): void {
    setSelectedId(null);
  }

  useEffect(() => {
    void loadTimers();
  }, []);

  async function doLogout(): Promise<void> {
    await logout();
    navigate('/login');
  }

  return (
    <>
      <div className="flex h-full flex-col">
        <header className="flex shrink-0 items-center justify-between border-b border-border bg-surface px-3 pt-[env(safe-area-inset-top)]">
          <button
            type="button"
            aria-label="Назад"
            className="flex h-10 w-10 items-center justify-center rounded-full text-lg active:bg-border/50"
            onClick={() => navigate('/')}
          >
            ←
          </button>
          <span className="text-xl">⏰</span>
          <button
            type="button"
            aria-label="Выйти"
            className="flex h-10 w-10 items-center justify-center rounded-full text-lg active:bg-border/50"
            onClick={() => void doLogout()}
          >
            🚪
          </button>
        </header>

        <main className="scroll-area flex-1 overflow-y-auto">
          {timersLoading ? (
            <Loader />
          ) : timersError ? (
            <div className="flex flex-col items-center gap-4 px-6 py-16">
              <EmptyState emoji="⚠️" text={timersError} />
              <button
                type="button"
                className="h-11 rounded-xl border border-border px-6 text-sm"
                onClick={() => void loadTimers()}
              >
                Повторить
              </button>
            </div>
          ) : timersNotes.length === 0 ? (
            <EmptyState emoji="⏰" text="Таймеров нет" />
          ) : (
            <div className="flex flex-col gap-2 px-3 py-3">
              {timersNotes.map((note) => (
                // Тап по строке — страница заметки (там снимают/переносят таймер)
                <button
                  key={note.id}
                  type="button"
                  className={`glass-card flex w-full touch-manipulation select-none flex-col gap-1 rounded-2xl px-4 py-3 text-left shadow-sm transition-[background-color,transform] active:scale-[0.98] [-webkit-touch-callout:none] ${
                    note.priority === 'high'
                      ? 'note-priority-high'
                      : note.priority === 'medium'
                        ? 'note-priority-medium'
                        : note.priority === 'low'
                          ? 'note-priority-low'
                          : ''
                  }`}
                  onClick={() => setSelectedId(note.id)}
                >
                  <span className="flex min-w-0 items-start gap-2.5">
                    {note.done && <span className="w-5 shrink-0 text-center text-sm leading-6">✅</span>}
                    <span
                      className={`line-clamp-2 min-w-0 flex-1 break-words text-[15px] leading-6 ${
                        note.done ? 'text-muted line-through' : 'text-content'
                      }`}
                      dangerouslySetInnerHTML={{ __html: firstLineHtml(note.text, note.entities) }}
                    />
                  </span>
                  <span className="pl-7 text-xs text-muted">
                    ⏰ {formatReminderAt(note.reminder_at!, note.reminder_repeat)}
                    {note.reminder_repeat === 'daily' ? '· 🔁 ежедневно' : '· 🔂 один раз'}
                  </span>
                </button>
              ))}
            </div>
          )}
        </main>
      </div>

      {selectedCache !== null && <NotePage note={selectedCache} onClose={closePage} />}
    </>
  );
}
